version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "80:8080"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/full-stack-ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: full-stack-ecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  springapimysql-net:

volumes:
  mysql-data:
    external: true